# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlook < Formula
  desc "Minimal SQLite database explorer"
  homepage "https://github.com/sxlgg/sqlook"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sxlgg/sqlook/releases/download/v0.1.0/sqlook_darwin_amd64.tar.gz"
      sha256 "72c28d5dd294c86722bb0144269e7b5db747171415de537031c3e260bbef731f"

      define_method(:install) do
        bin.install "sqlook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sxlgg/sqlook/releases/download/v0.1.0/sqlook_darwin_arm64.tar.gz"
      sha256 "b62d79390275ee5f2f6a18023369f453311e1733afb1993e4a20fb7f1b60e894"

      define_method(:install) do
        bin.install "sqlook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sxlgg/sqlook/releases/download/v0.1.0/sqlook_linux_amd64.tar.gz"
      sha256 "3a7ad37f3810562aa28b83a1732b5199c5a0834e2090a6593de3be738d15c838"
      define_method(:install) do
        bin.install "sqlook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sxlgg/sqlook/releases/download/v0.1.0/sqlook_linux_arm64.tar.gz"
      sha256 "38c0886d2aeaf9c97296823e6c5fe803ef76e2e7caef315b2161d744693aef9d"
      define_method(:install) do
        bin.install "sqlook"
      end
    end
  end
end
