# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlook < Formula
  desc "Minimal SQLite database explorer"
  homepage "https://github.com/sxlgg/sqlook"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sxlgg/sqlook/releases/download/v0.2.0/sqlook_darwin_amd64.tar.gz"
      sha256 "26a68197e5aefb20209d08bc30690c32790b6acc6ef1487f2c0b79db34ac5b2e"

      define_method(:install) do
        bin.install "sqlook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sxlgg/sqlook/releases/download/v0.2.0/sqlook_darwin_arm64.tar.gz"
      sha256 "caee5496216ffe48b2dec7b762ba757e91c64a25b280b4b398825e673cc08266"

      define_method(:install) do
        bin.install "sqlook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sxlgg/sqlook/releases/download/v0.2.0/sqlook_linux_amd64.tar.gz"
      sha256 "15b955844f254aa6830cf6be9cf2c1920e347e60baa22ae29b3a65c864a31d2f"
      define_method(:install) do
        bin.install "sqlook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sxlgg/sqlook/releases/download/v0.2.0/sqlook_linux_arm64.tar.gz"
      sha256 "72c2b596313d6c7391a58082c7664a82cb7df66b61d17966a5e991441223db55"
      define_method(:install) do
        bin.install "sqlook"
      end
    end
  end
end
